## macroeconomic predictors

In [1]:
import pandas as pd
import numpy as np
import datetime
import math
import matplotlib.pyplot as plt
import statistics

In [36]:
data = pd.read_excel('C:\\Judy\\MFE Courses\\431_Quantitative_Asset_Management\\Final_Project\\PredictorData2020.xlsx')

In [37]:
data

,yyyymm,Index,D12,E12,b/m,tbl,AAA,BAA,lty,ntis,Rfree,infl,ltr,corpr,svar,csp,CRSP_SPvw,CRSP_SPvwx
0,187101,4.44,0.260000,0.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,187102,4.50,0.260000,0.400000,NaN,NaN,NaN,NaN,NaN,NaN,0.004967,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,187103,4.61,0.260000,0.400000,NaN,NaN,NaN,NaN,NaN,NaN,0.004525,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,187104,4.74,0.260000,0.400000,NaN,NaN,NaN,NaN,NaN,NaN,0.004252,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,187105,4.86,0.260000,0.400000,NaN,NaN,NaN,NaN,NaN,NaN,0.004643,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1795,202008,3500.31,59.128628,98.556667,0.235975,0.0010,0.0225,0.0327,0.0065,-0.008504,0.000100,0.003153,-0.0349,-0.0488,0.000743,NaN,0.072068,0.070308
1796,202009,3363.00,58.851237,98.220000,0.241482,0.0011,0.0231,0.0336,0.0068,-0.005698,0.000100,0.001393,0.0080,0.0041,0.004907,NaN,-0.038151,-0.039366
1797,202010,3269.96,58.660440,96.856667,0.253146,0.0010,0.0235,0.0344,0.0079,-0.001895,0.000100,0.000415,-0.0238,-0.0190,0.003661,NaN,-0.026409,-0.027507
1798,202011,3621.63,58.469643,95.493333,0.226352,0.0009,0.0230,0.0330,0.0087,-0.005262,0.000100,-0.000611,0.0093,0.0509,0.002492,NaN,0.109403,0.107623
1799,202012,3756.07,58.278846,94.130000,0.219195,0.0009,0.0226,0.0316,0.0093,-0.000094,0.000100,0.000941,-0.0115,0.0000,0.000678,NaN,0.041573,0.040138

In [16]:
#data['date'] = data['yyyymm'].astype(str)
#data['Year'] = data['date'].apply(lambda x: int(x[0:4]))
#data['Month'] = data['date'].apply(lambda x: int(x[4:6]))

In [38]:
#Dividend Price Ratio
data['dp']= np.log(data['D12']) - np.log(data['Index'])

In [39]:
#Earnings-price ratio
data['ep'] = np.log(data['E12']) - np.log(data['Index'])

In [40]:
# Term Spread
data['tms'] = data['lty'] - data['tbl']

In [41]:
#default spread
data['dfy'] = data['BAA'] - data['AAA']

In [42]:
#data['bm'] : Book-to-Market Ratio(Given)
#data['ntis'] :net equity expansion(Given)
#data['tbl'] :Treasury-bill rate (Given)
#data[svar'] :stock variance (Given)

In [ ]:
data[['yyyymm','dp','ep','tms','dfy','bm','ntis','tbl']].to_csv("C:\\Judy\\MFE Courses\\431_Quantitative_Asset_Management\\Final_Project\\macroeconomic.xlsx")